### ISSUE TITLE
[BUG] IPv6 UDP not works under TUN mode

### ISSUE THREAD

**Issue by f4nff** [HyNetwork/hysteria#394]
### 功能描述

经过测试，ipv4的tun模式下udp是正常的，但是ipv6的udp不通，TCP是通的。

### 这个功能的必要性

不能使用ipv6的dns，还有quic协议。

**Comment by f4nff** [comment]
```
{
	"server": "ipv6.7mb.xyz:12346", 
  "protocol": "udp",
  "up_mbps": 30,
  "down_mbps": 300,
  "retry": -1, 
  "retry_interval": 5,
  "tun": {
    "name": "tun0",
	"timeout": 60,
    "persist": false

  },
  "server_name": "1-courier.push.apple.com", 
  "insecure": true, 
  "recv_window_conn": 15728640, 
  "recv_window": 67108864, 
  "disable_mtu_discovery": false

}
```

**Comment by haruue** [comment]
Tested and `relay_udps` works but TUN failed.
Seems like a bug of TUN mode.

**Comment by haruue** [comment]
This should be a bug of go-tun2socks.
https://github.com/HyNetwork/hysteria/blob/af2e0e9676fe25c3f7f0ef3bff43ba44d031d097/pkg/tun/udp.go#L54

Tested and we've already called `conn.WriteFrom()` with the correct packet, but the client received nothing from tun, and `err == nil`.

I think it is time to construct our own tun2socks frameworks with a similar API, or just remove the TUN mode.

对于 Hysteria 用户， 可以考虑暂时切换到 `redirect_udp` 或者 `tproxy_udp` 。

**Comment by f4nff** [comment]
把tun2socks替换成为 https://github.com/xjasonlyu/tun2socks 就好了，而且是纯go，编译还方便。

**Comment by f4nff** [comment]
tun 模式适合在openwrt里面用，很方便。

**Comment by f4nff** [comment]
```
root@OpenWrt:~/hy# ./hy-openwrt --log-level panic
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7ffbb30a3230 pc=0xc143e0]

runtime stack:
runtime.throw({0xe1b5f8?, 0x7ffbb3306448?})
        /home/go/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
        /home/go/src/runtime/signal_unix.go:802 +0x389

goroutine 47 [syscall, locked to thread]:
runtime.cgocall(0xc14400, 0xc000350ba8)
        /home/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000350b80 sp=0xc000350b48 pc=0x404b7c
github.com/eycorsican/go-tun2socks/core._Cfunc_get_conn_key_val(0x7ffbb30a3230)
        _cgo_gotypes.go:359 +0x48 fp=0xc000350ba8 sp=0xc000350b80 pc=0xa81a88
github.com/eycorsican/go-tun2socks/core.getConnKeyVal.func1(0x7ffbb31343c0?)
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/tcp_conn_map.go:64 +0x3a fp=0xc000350be0 sp=0xc000350ba8 pc=0xa892ba
github.com/eycorsican/go-tun2socks/core.getConnKeyVal(0x40e685?)
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/tcp_conn_map.go:64 +0x19 fp=0xc000350bf8 sp=0xc000350be0 pc=0xa89259
github.com/eycorsican/go-tun2socks/core.tcpErrFn(0x405186?, 0xf3)
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/tcp_callback_export.go:135 +0x25 fp=0xc000350c68 sp=0xc000350bf8 pc=0xa86285
_cgoexp_6669f3000c98_tcpErrFn(0x7ffbb325ccc7?)
        _cgo_gotypes.go:993 +0x25 fp=0xc000350c88 sp=0xc000350c68 pc=0xa8ac25
runtime.cgocallbackg1(0xa8ac00, 0xc000350e40?, 0x0)
        /home/go/src/runtime/cgocall.go:314 +0x2c2 fp=0xc000350d58 sp=0xc000350c88 pc=0x4050a2
runtime.cgocallbackg(0xc0000036c0?, 0x300000002?, 0xc0000036c0?)
        /home/go/src/runtime/cgocall.go:233 +0x109 fp=0xc000350de8 sp=0xc000350d58 pc=0x404d29
runtime.cgocallbackg(0xa8ac00, 0x7ffbb325cdd7, 0x0)
        <autogenerated>:1 +0x2f fp=0xc000350e10 sp=0xc000350de8 pc=0x46a0af
runtime.cgocallback(0x404ba5, 0xc14260, 0xc000350ea0)
        /home/go/src/runtime/asm_amd64.s:971 +0xb4 fp=0xc000350e38 sp=0xc000350e10 pc=0x467b14
runtime.systemstack_switch()
        /home/go/src/runtime/asm_amd64.s:436 fp=0xc000350e40 sp=0xc000350e38 pc=0x465b20
runtime.cgocall(0xc14260, 0xc000350ea0)
        /home/go/src/runtime/cgocall.go:167 +0x85 fp=0xc000350e78 sp=0xc000350e40 pc=0x404ba5
github.com/eycorsican/go-tun2socks/core._Cfunc_tcp_abort(0x7ffbb3306430)
        _cgo_gotypes.go:654 +0x45 fp=0xc000350ea0 sp=0xc000350e78 pc=0xa82865
github.com/eycorsican/go-tun2socks/core.(*tcpConn).abortInternal.func1(0xc0001fa100?)
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/tcp_conn.go:432 +0x3b fp=0xc000350ed8 sp=0xc000350ea0 pc=0xa88c9b
github.com/eycorsican/go-tun2socks/core.(*tcpConn).abortInternal(0x13?)
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/tcp_conn.go:432 +0x28 fp=0xc000350ef8 sp=0xc000350ed8 pc=0xa88c28
github.com/eycorsican/go-tun2socks/core.(*tcpConn).checkAborting(0xc0002bf1d0?)
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/tcp_conn.go:339 +0x8b fp=0xc000350f50 sp=0xc000350ef8 pc=0xa881ab
github.com/eycorsican/go-tun2socks/core.(*tcpConn).checkState(0xc0001fa100)
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/tcp_conn.go:362 +0x45 fp=0xc000350f70 sp=0xc000350f50 pc=0xa88445
github.com/eycorsican/go-tun2socks/core.(*tcpConn).Abort(0xc0001fa100)
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/tcp_conn.go:444 +0xa5 fp=0xc000350f90 sp=0xc000350f70 pc=0xa88d85
github.com/eycorsican/go-tun2socks/core.newTCPConn.func2()
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/tcp_conn.go:114 +0x151 fp=0xc000350fe0 sp=0xc000350f90 pc=0xa86cf1
runtime.goexit()
        /home/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000350fe8 sp=0xc000350fe0 pc=0x467d41
created by github.com/eycorsican/go-tun2socks/core.newTCPConn
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/tcp_conn.go:111 +0x525

goroutine 1 [chan receive]:
main.client(0xc000314300)
        /home/hysteria/cmd/client.go:474 +0x18ca
main.glob..func4(0x0?, {0x0?, 0x0?, 0x0?})
        /home/hysteria/cmd/main.go:98 +0x395
main.glob..func3(0x14a6960?, {0xc0002b4900?, 0x2?, 0x3?})
        /home/hysteria/cmd/main.go:74 +0x2c
github.com/spf13/cobra.(*Command).execute(0x14a6960, {0xc0002c6490, 0x2, 0x3})
        /home/gopkg/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x14a6960)
        /home/gopkg/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/gopkg/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/hysteria/cmd/main.go:180 +0x25

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x7ffbb3295118, 0x72)
        /home/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0002a8380?, 0xc0002cea00?, 0x0)
        /home/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /home/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).RawRead(0xc0002a8380, 0xc0001c4c60)
        /home/go/src/internal/poll/fd_unix.go:766 +0x145
net.(*rawConn).Read(0xc000290130, 0xc77f60?)
        /home/go/src/net/rawconn.go:43 +0x45
golang.org/x/net/internal/socket.(*syscaller).recvmmsg(0xc0001885e8, {0xf49418?, 0xc000290130?}, {0xc0000fe800?, 0xe590e0?, 0x0?}, 0x50?)
        /home/gopkg/pkg/mod/golang.org/x/net@v0.0.0-20220630215102-69896b714898/internal/socket/mmsghdr_unix.go:121 +0x94
golang.org/x/net/internal/socket.(*Conn).recvMsgs(0xc0002b4940, {0xc000300840?, 0x8, 0x8}, 0xc00028ed80?)
        /home/gopkg/pkg/mod/golang.org/x/net@v0.0.0-20220630215102-69896b714898/internal/socket/rawconn_mmsg.go:25 +0x199
golang.org/x/net/internal/socket.(*Conn).RecvMsgs(...)
        /home/gopkg/pkg/mod/golang.org/x/net@v0.0.0-20220630215102-69896b714898/internal/socket/socket.go:267
golang.org/x/net/ipv4.(*payloadHandler).ReadBatch(0xc0002bec40, {0xc000300840?, 0x80?, 0xc000060e80?}, 0x8a1417?)
        /home/gopkg/pkg/mod/golang.org/x/net@v0.0.0-20220630215102-69896b714898/ipv4/batch.go:80 +0x57
github.com/lucas-clemente/quic-go.(*oobConn).ReadPacket(0xc0002a8400)
        /home/gopkg/pkg/mod/github.com/tobyxdd/quic-go@v0.28.2-0.20220806194731-5be744e08984/sys_conn_oob.go:150 +0x6d2
github.com/lucas-clemente/quic-go.(*packetHandlerMap).listen(0xc000316160)
        /home/gopkg/pkg/mod/github.com/tobyxdd/quic-go@v0.28.2-0.20220806194731-5be744e08984/packet_handler_map.go:355 +0x70
created by github.com/lucas-clemente/quic-go.newPacketHandlerMap
        /home/gopkg/pkg/mod/github.com/tobyxdd/quic-go@v0.28.2-0.20220806194731-5be744e08984/packet_handler_map.go:171 +0x2d6

goroutine 48 [sleep]:
time.Sleep(0xdf8470d3d)
        /home/go/src/runtime/time.go:194 +0x12e
github.com/tobyxdd/hysteria/pkg/tun.(*Server).fetchUDPInput.func2()
        /home/hysteria/pkg/tun/udp.go:37 +0x45
created by github.com/tobyxdd/hysteria/pkg/tun.(*Server).fetchUDPInput
        /home/hysteria/pkg/tun/udp.go:30 +0x14a

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x7ffbb3294f38, 0x72)
        /home/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00039a180?, 0xc000174000?, 0x0)
        /home/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /home/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc00039a180, {0xc000174000, 0xe61, 0xe61})
        /home/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00039a180, {0xc000174000?, 0xd29201?, 0xc0002b46a0?})
        /home/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00038e018, {0xc000174000?, 0x8f1?, 0xc0002b46a0?})
        /home/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0000ac240, {0xc000174000?, 0x0?, 0x35?})
        /home/go/src/crypto/tls/conn.go:785 +0x3d
bytes.(*Buffer).ReadFrom(0xc0003a8278, {0xf41860, 0xc0000ac240})
        /home/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0003a8000, {0xf42bc0?, 0xc00038e018}, 0xc000174575?)
        /home/go/src/crypto/tls/conn.go:807 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0003a8000, 0x0)
        /home/go/src/crypto/tls/conn.go:614 +0x116
crypto/tls.(*Conn).readRecord(...)
        /home/go/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0xc0003a8000, {0xc000175000, 0x1000, 0x6afbe0?})
        /home/go/src/crypto/tls/conn.go:1285 +0x16f
bufio.(*Reader).Read(0xc00035d740, {0xc0002cb0e0, 0x9, 0x6cc562?})
        /home/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0xf41640, 0xc00035d740}, {0xc0002cb0e0, 0x9, 0x9}, 0x9)
        /home/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
        /home/go/src/io/io.go:350
net/http.http2readFrameHeader({0xc0002cb0e0?, 0x9?, 0xc00060f3e0?}, {0xf41640?, 0xc00035d740?})
        /home/go/src/net/http/h2_bundle.go:1566 +0x6e
net/http.(*http2Framer).ReadFrame(0xc0002cb0a0)
        /home/go/src/net/http/h2_bundle.go:1830 +0x95
net/http.(*http2clientConnReadLoop).run(0xc00034ff98)
        /home/go/src/net/http/h2_bundle.go:8815 +0x130
net/http.(*http2ClientConn).readLoop(0xc00033a600)
        /home/go/src/net/http/h2_bundle.go:8711 +0x6f
created by net/http.(*http2Transport).newClientConn
        /home/go/src/net/http/h2_bundle.go:7439 +0xa65

goroutine 42 [IO wait]:
internal/poll.runtime_pollWait(0x7ffbb3295028, 0x72)
        /home/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00035c360?, 0xc000323800?, 0x1)
        /home/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /home/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc00035c360, {0xc000323800, 0x5dc, 0x5dc})
        /home/go/src/internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
        /home/go/src/os/file_posix.go:31
os.(*File).Read(0xc000290158, {0xc000323800?, 0x22d?, 0x5dc?})
        /home/go/src/os/file.go:119 +0x5e
io.copyBuffer({0x7ffbb31db658, 0xc000319740}, {0x7ffbb31db678, 0xc0003196e0}, {0xc000323800, 0x5dc, 0x5dc})
        /home/go/src/io/io.go:426 +0x1b2
io.CopyBuffer({0x7ffbb31db658?, 0xc000319740?}, {0x7ffbb31db678?, 0xc0003196e0?}, {0xc000323800?, 0x0?, 0x0?})
        /home/go/src/io/io.go:399 +0x3c
github.com/tobyxdd/hysteria/pkg/tun.(*Server).ListenAndServe(0xc0002bf1d0)
        /home/hysteria/pkg/tun/server.go:60 +0x16e
main.client.func5()
        /home/hysteria/cmd/client.go:296 +0x1bf
created by main.client
        /home/hysteria/cmd/client.go:254 +0x13e5

goroutine 43 [select]:
github.com/eycorsican/go-tun2socks/core.NewLWIPStack.func5()
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/lwip.go:82 +0x85
created by github.com/eycorsican/go-tun2socks/core.NewLWIPStack
        /home/gopkg/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/lwip.go:80 +0x12a

goroutine 66 [select]:
github.com/lucas-clemente/quic-go.(*closedLocalConn).run(0xc000326ee0)
        /home/gopkg/pkg/mod/github.com/tobyxdd/quic-go@v0.28.2-0.20220806194731-5be744e08984/closed_conn.go:51 +0x85
created by github.com/lucas-clemente/quic-go.newClosedLocalConn
        /home/gopkg/pkg/mod/github.com/tobyxdd/quic-go@v0.28.2-0.20220806194731-5be744e08984/closed_conn.go:45 +0x190
```

**Comment by f4nff** [comment]
github.com/eycorsican/go-tun2socks

这个玩意实在不咋地。

**Comment by f4nff** [comment]
```
go: downloading github.com/tobyxdd/quic-go v0.28.1-0.20220706211558-7780039ad599
go: downloading github.com/miekg/dns v1.1.46
go: downloading github.com/xjasonlyu/tun2socks/v2 v2.4.1
go: downloading go.uber.org/atomic v1.9.0
go: downloading gvisor.dev/gvisor v0.0.0-20220405222207-795f4f0139bb
go: downloading golang.org/x/time v0.0.0-20220224211638-0e9765cccd65
go: downloading github.com/google/btree v1.0.1
```

测试ing

**Comment by f4nff** [comment]
```
root@OpenWrt:~/hy# ./server -h
Segmentation fault
```

编译之后，openwrt运行不起来，咋回事？

```
export PATH=/home/openwrt-sdk-22.03.0-rc6-x86-64_gcc-11.2.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/bin:$PATH
export STAGING_DIR=/home/openwrt-sdk-22.03.0-rc6-x86-64_gcc-11.2.0_musl.Linux-x86_64/staging_dir
CGO_ENABLED=1 CC=x86_64-openwrt-linux-musl-gcc CXX=x86_64-openwrt-linux-musl-g++ GOOS=linux GOARCH=amd64 go build -o server -ldflags '-s -w --extldflags "-static -fpic"'

```

**Comment by tobyxdd** [comment]
你关掉 cgo 试试，这个版本应该不需要 cgo 了

**Comment by f4nff** [comment]
可以运行了，刚才空间不够了。

**Comment by f4nff** [comment]
```
C:\Users\ll>nslookup www.qq.com dns.google
服务器:  dns.google
Address:  2001:4860:4860::8888

非权威应答:
名称:    e6156.dscf.akamaiedge.net
Addresses:  2600:1406:bc00:692::180c
          2600:1406:bc00:685::180c
          23.205.197.174
Aliases:  www.qq.com
          news.qq.com.edgekey.net
```

ipv6 udp  也好了。

**Comment by f4nff** [comment]
目前测试，udp ipv6 正常，没发现闪退现象，但是确定到底有没有问题，还需要几天，但是我是退回golang1.18.5编译的。
